// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCErxKEng3ooKM0iIdanDelFT-dfp-Y0Js',
    appId: '1:240086523511:web:6de977ec827bcf331eb072',
    messagingSenderId: '240086523511',
    projectId: 'app-rpgo-6061a',
    authDomain: 'app-rpgo-6061a.firebaseapp.com',
    storageBucket: 'app-rpgo-6061a.firebasestorage.app',
    measurementId: 'G-CR7CPHG0VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGwmjxIirMOT_NZrFQ19WvwmzVtxwFgv0',
    appId: '1:240086523511:android:aeb4c62b28c6d3f31eb072',
    messagingSenderId: '240086523511',
    projectId: 'app-rpgo-6061a',
    storageBucket: 'app-rpgo-6061a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAdRCaJwjDsKNOoyiRF9D_vPyE52bLUBw',
    appId: '1:240086523511:ios:aec277ba5ef4fc5e1eb072',
    messagingSenderId: '240086523511',
    projectId: 'app-rpgo-6061a',
    storageBucket: 'app-rpgo-6061a.firebasestorage.app',
    iosBundleId: 'com.example.appRpg',
  );
}
